-- ============================================================
-- 0024 — UNIFICATIE, FASE 4: compatibiliteitslaag voor de Prospectie-app
-- ============================================================
-- De Prospectie-app blijft werken met een platte `prospects`-tabel, maar die
-- bestaat hier als een VIEW bovenop bedrijf + contact, met INSTEAD OF-triggers
-- die insert/update/delete naar de juiste tabellen routeren. Zo komt elke nieuwe
-- prospect meteen in de gedeelde database, zonder de app te herschrijven.
--
-- Mapping (oud prospects  ->  nieuw model):
--   titel      -> contact.aanspreektitel      bedrijf   -> bedrijf.naam
--   voornaam   -> contact.voornaam            categorie -> contact.cat1
--   naam       -> contact.achternaam          notities  -> contact.cat2  (app-label "CAT 2")
--   email      -> contact.email               status    -> contact.status (nieuw)
--   telefoon   -> contact.gsm                 datum     -> contact.created_at (afgeleid)
--   verloop/samenvatting/volgende_stap(_datum) -> gelijknamige contact-velden
--
-- VEILIG / ADDITIEF: 1 nieuwe kolom (contact.status), 1 nieuwe tabel (templates),
-- 1 view + triggers. Geen bestaande data gewijzigd.
-- ============================================================

-- ---- (a) statusveld + integer-surrogaatsleutel op contact ----
-- De Prospectie-app zet id's ONquoted in z'n HTML-handlers (toggleRow(22,...)),
-- dus de view moet een INTEGER-id teruggeven, niet de uuid. `rijnr` (identity)
-- levert dat; bestaande rijen worden automatisch genummerd bij het toevoegen.
alter table contact add column if not exists status text;
alter table contact add column if not exists rijnr  bigint generated by default as identity;
create unique index if not exists contact_rijnr_uniek on contact (rijnr);

-- ---- (b) templates-tabel (mailsjablonen; data wordt apart overgezet) ----
create table if not exists templates (
  categorie text primary key,
  subject   text,
  body      text,
  hints     text
);
alter table templates enable row level security;
drop policy if exists dev_all_templates on templates;
create policy dev_all_templates on templates for all to anon, authenticated using (true) with check (true);

-- ---- (c) de compatibiliteits-view ----
drop view if exists prospects;
create view prospects as
select
  c.rijnr                              as id,
  c.aanspreektitel                     as titel,
  c.voornaam                           as voornaam,
  c.achternaam                         as naam,
  c.email                              as email,
  c.gsm                                as telefoon,
  b.naam                               as bedrijf,
  c.cat1                               as categorie,
  c.cat2                               as notities,
  to_char(c.created_at, 'DD/MM/YYYY')  as datum,
  c.status                             as status,
  c.created_at                         as created_at,
  c.verloop                            as verloop,
  c.samenvatting                       as samenvatting,
  c.volgende_stap                      as volgende_stap,
  c.volgende_stap_datum                as volgende_stap_datum,
  c.bedrijf_id                         as bedrijf_id
from contact c
join bedrijf b on b.id = c.bedrijf_id;

-- Zoek een bedrijf op genormaliseerde naam of maak het aan; geeft het id terug.
create or replace function _vind_of_maak_bedrijf(p_naam text) returns uuid
language plpgsql as $$
declare v_id uuid; v_naam text := btrim(coalesce(p_naam, ''));
begin
  if v_naam = '' then v_naam := 'Onbekend bedrijf'; end if;
  select id into v_id from bedrijf where naam_norm = norm_naam(v_naam) limit 1;
  if v_id is null then
    insert into bedrijf (naam, status, bron) values (v_naam, 'prospect', 'prospectie')
    returning id into v_id;
  end if;
  return v_id;
end $$;

-- ---- (d) INSTEAD OF-triggers ----
create or replace function prospects_insert() returns trigger language plpgsql as $$
declare
  v_bedrijf_id uuid;
  v_naam text := btrim(coalesce(new.bedrijf, ''));
begin
  if v_naam = '' then
    v_naam := nullif(btrim(coalesce(new.voornaam,'') || ' ' || coalesce(new.naam,'')), '');
  end if;
  v_bedrijf_id := _vind_of_maak_bedrijf(v_naam);

  insert into contact (
    bedrijf_id, aanspreektitel, voornaam, achternaam, email, gsm,
    cat1, cat2, status, verloop, samenvatting, volgende_stap, volgende_stap_datum,
    nog_te_contacteren, bron
  ) values (
    v_bedrijf_id, new.titel, new.voornaam, new.naam, new.email, new.telefoon,
    new.categorie, new.notities, new.status, new.verloop, new.samenvatting,
    new.volgende_stap, new.volgende_stap_datum,
    coalesce(new.status, '') = 'Nog te contacteren', 'prospectie'
  ) returning rijnr into new.id;

  new.bedrijf    := (select naam from bedrijf where id = v_bedrijf_id);
  new.bedrijf_id := v_bedrijf_id;
  new.created_at := now();
  new.datum      := to_char(now(), 'DD/MM/YYYY');
  return new;
end $$;

create or replace function prospects_update() returns trigger language plpgsql as $$
declare v_bedrijf_id uuid;
begin
  update contact set
    aanspreektitel      = new.titel,
    voornaam            = new.voornaam,
    achternaam          = new.naam,
    email               = new.email,
    gsm                 = new.telefoon,
    cat1                = new.categorie,
    cat2                = new.notities,
    status              = new.status,
    verloop             = new.verloop,
    samenvatting        = new.samenvatting,
    volgende_stap       = new.volgende_stap,
    volgende_stap_datum = new.volgende_stap_datum
  where rijnr = old.id;

  -- Bedrijfsnaam gewijzigd? koppel dit contact aan het (nieuwe/bestaande) bedrijf.
  if btrim(coalesce(new.bedrijf,'')) <> '' and coalesce(new.bedrijf,'') is distinct from coalesce(old.bedrijf,'') then
    v_bedrijf_id := _vind_of_maak_bedrijf(new.bedrijf);
    update contact set bedrijf_id = v_bedrijf_id where rijnr = old.id;
  end if;
  return new;
end $$;

create or replace function prospects_delete() returns trigger language plpgsql as $$
begin
  delete from contact where rijnr = old.id;
  return old;
end $$;

drop trigger if exists trg_prospects_insert on prospects;
drop trigger if exists trg_prospects_update on prospects;
drop trigger if exists trg_prospects_delete on prospects;
create trigger trg_prospects_insert instead of insert on prospects for each row execute function prospects_insert();
create trigger trg_prospects_update instead of update on prospects for each row execute function prospects_update();
create trigger trg_prospects_delete instead of delete on prospects for each row execute function prospects_delete();

-- ---- (e) rechten (dev: anon mag alles, zoals de andere tabellen) ----
grant select, insert, update, delete on prospects to anon, authenticated;
grant select, insert, update, delete on templates to anon, authenticated;

-- PostgREST de nieuwe view/tabel meteen laten oppikken.
notify pgrst, 'reload schema';
